### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by gloomy-ghost**
A short term fix to stop 404 as we haven't got any ideas of choosing an icon.

### CODE REVIEW

**Comment by lilydjwg** [comment]
I've added a conditional comment for IE. We still have IE6 (`Mozilla/5.0 (Windows; U; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727; BIDUBrowser 7.6)`)....

**Comment by gloomy-ghost** [comment]
I have nothing to comment about IE6... How can users who know this image paste service still use such an outdated browser...

**Comment by lilydjwg** [comment]
Errr, in the past there was only one 404, now there are two.... I don't know why the conditional comment doesn't work well, and there are browser still asking for `/favicon.ico`.

**Comment by gloomy-ghost** [comment]
Just tried on Chrome, Firefox, Edge and IE11, couldn't find any problems... Which browser did you use?

**Comment by lilydjwg** [comment]
Not mine. I see requests from the access log. Maybe we have to live with those 404's.

**Comment by gloomy-ghost** [comment]
`<!--[if gte IE 8]>-->` isn't a valid conditional comment anyway, remove it?

What does IE6 do with a data URI? I think it's ok if IE just ignore the URI without crashing. 😄

**Comment by lilydjwg** [comment]
OK, I've reverted it.

IE6 requests the `/data:,` URL.

**Pull request merged**
